### ISSUE TITLE
typo a380x-briefing 

### ISSUE THREAD

**Issue by tangottt** [flybywiresim/docs#1038]
under docs/pilots-corner/a380x/a380x-briefing/flight-deck/ovhd/air.md , the header "CKPI selector" should be "CKPT selector"

https://github.com/flybywiresim/docs/blob/primary/docs/pilots-corner/a380x/a380x-briefing/flight-deck/ovhd/air.md#ckpi-selector

**Comment by frankkopp** [comment]
Fixed - thanks for the report
