### ISSUE TITLE
A380X initial climb pitch attitude target

### ISSUE THREAD

**Issue by donstim** [flybywiresim/docs#1066]
The A380X beginner's guide documentation for takeoff and climbout appears to use the same initial pitch attitude targets as for the A32NX.
![Screenshot 2024-11-22 194006](https://github.com/user-attachments/assets/f343bcf4-f479-4a88-98da-c17ad896be78)
![Screenshot 2024-11-22 194015](https://github.com/user-attachments/assets/a914b088-87f2-4860-96bb-8403c749083d)

According to the A380 Flight Crew Training Manual, the normal initial pitch attitude target for the A380 should be 12.5 degrees (obtained using the same 2-3 degrees per second rotation rate). Excessively high rotation rates or angles can lead to tailstrikes or even unintended alpha floor activation (especially, I bet for overly aggressive flight simmers).
![Screenshot 2024-11-22 194917](https://github.com/user-attachments/assets/ec5a17e7-5765-44e0-81e4-3fd53c774036)

**Comment by frankkopp** [comment]
![image](https://github.com/user-attachments/assets/114c9f53-47bc-4a27-a970-430acfddb2c8)

Fixed - thanks!
