### ISSUE TITLE
Pilot Briefing: Overhead panels - Accuracy check 

### ISSUE THREAD

**Issue by komp1821** [flybywiresim/docs#211]
### Preface 

Hey docs team! Here is the first part of my review of your Pilot Briefing. This is the overhead only. The rest will follow in a separate issue. I already told you: You did a fantastic job! I'm impressed. Please take the following list as an offer, a suggestion, not as criticism. I know it looks huge, but it isn't, compared to the overall size of the Pilot Briefing. 

Things I didn't explicitly watch out for:
- grammar
- punctuation
- other language-related stuff.
I'm not a native speaker, and I think we have more qualified people for the job.

### General

- The explanation of the FAULT lights is often accompanied by a reference to ECAM cautions. Technically, the ECAM caution is completely independent from the so called "local warnings". Ideally they occur at nearly the same time, but there _can_ be situations in which the FAULT light comes on without any ECAM event. I'll leave it up to you.

### Summary

- [ ] **Overhead Aft -> Emergency Locator Transmitter Panel**
- [ ] **Overhead Aft -> Maintenance Panel -> CVR Headset**
- [ ] **Overhead Aft -> Maintenance Panel -> BLUE PUMP OVRD**
- [ ] **Overhead Aft -> Pedestal Light and Audio 3 Switch -> 3rd Audio Switch**
- [ ] **Overhead Fwd -> Air Condition Control Panel -> APU BLEED pushbutton**
- [ ] **Overhead Fwd -> ADIRS Panel -> Operation**
- [ ] **Overhead Fwd -> Auxiliary Power Unit-> MASTER SW**
- [ ] **Overhead Fwd -> Auxiliary Power Unit-> START**
- [ ] **Overhead Fwd -> Cabin Pressurization-> MODE SEL**
- [ ] **Overhead Fwd -> Calls Panel ->  Description**
- [ ] **Overhead Fwd -> Calls Panel ->  Usage -> MECH**
- [ ] **Overhead Fwd -> Calls Panel ->  Usage -> FWD/AFT**
- [ ] **Overhead Fwd -> Cargo Smoke Panel ->  Usage -> SMOKE light**
- [ ] **Overhead Fwd -> Cargo Smoke Panel ->  Usage -> DISCH light**
- [ ] **Overhead Fwd -> Electrical System Control Panel -> Usage -> AC ESS FEED**
- [ ] **Overhead Fwd -> Emergency Electric Power Panel -> Usage -> GEN 1 LINE**
- [ ] **Overhead Fwd -> Fire Control Panel -> Usage -> APU FIRE**
- [ ] **Overhead Fwd -> Fire Control Panel -> Usage -> APU AGENT**
- [ ] **Overhead Fwd -> Fire Control Panel -> Usage -> APU TEST**
- [ ] **Overhead Fwd -> Fuel Control Panel -> Description**
- [ ] **Overhead Fwd -> Fuel Control Panel -> Usage -> CTR TK PUMP 1 + 2**
- [ ] **Overhead Fwd -> Fuel Control Panel -> Description**
- [ ] **Overhead Fwd -> Fuel Control Panel -> Usage -> CVR ERASE**

Hope this makes it easier for you to track the issues.

---

### Overhead Aft

**Overhead Aft -> Emergency Locator Transmitter Panel**

> Emergency Locator Transmitters are mounted in the back of the aircraft, and are designed to be triggered upon impact or may be manually activated using the remote switch and control panel indicator in the cockpit.

There is only one ELT mounted in the back of the aircraft. An option for a second ELT used to exist, but it’s not common anymore. Instead, there is an additional handheld ELT mounted in the cockpit wardrobe.

> An audio alert starts and a distress signal is transmitted for search and rescue upon activation.

The audio alert (i.e. the distress signal) is only audible when the correct frequency (in this case 121.500) is selected in the RMP (and the corresponding reception knobs of the ACP are set accordingly). 

**Overhead Aft -> Maintenance Panel -> CVR Headset**

> Headphone output to monitor the Cockpit Voice Recorder, e.g., for testing.

Scratch the "e. g.". It's the sole purpose of this jack.

**Overhead Aft -> Maintenance Panel -> BLUE PUMP OVRD**

> OFF: The blue electric pump is off

That's correct as long as the AUTO condition isn't fulfilled (at least 1 engine running). I'd change it to something like "OFF: The blue electric pump is controlled by the the automatic logic".

**Overhead Aft -> Pedestal Light and Audio 3 Switch -> 3rd Audio Switch**

> Audio from the 3rd radio can be switched to either jump seat (NORM), CAPT or F/O.

a) I don't like the title "3rd Audio Switch" and would prefer something like AUDIO SWITCHING, like the legend on the panel. b) This switch has essentially nothing to do with the _radios_. It switches the ACP and transfers its output to the Captain's or FO's headphones. If set to CAPT 3, the captain can control their volume through the ACP3:

![audio switching](https://user-images.githubusercontent.com/71044068/133243827-dbe08e59-fcfb-490f-b7d7-dfc0d67b33cb.png)

---

### Overhead Fwd

**Overhead Fwd -> Air Condition Control Panel -> APU BLEED pushbutton**

> FAULT: Amber Light and an ECAM caution, when the system detects an APU leak.

I'm not 100% sure and don't have the time to confirm right now, but I think there are also other conditions for the FAULT light to come on. This is more a reminder to myself to verify again. If anyone else wants to pick it up, feel free!

**Overhead Fwd -> ADIRS Panel -> Operation**

> ON BATT will then flash as a self-test at the start of alignment. If one or more of the ADIRU's are running on battery power, ON BATT will display constantly.

Can we replace "flash" with something like "come on for a defined time" or something? Flashing sounds to me like it goes ON-OFF-ON-OFF... continously.

**Overhead Fwd -> Auxiliary Power Unit-> MASTER SW**

> APU fuel pump operates if fuel pumps are not in operation.

To be precise, one fuel pump in the **left** wing tank is sufficient. The control depends on fuel pressure availability, not the status of the fuel pump. Could be renamed into "if at least one fuel pump in the left wing tank is in operation".

> OFF: Air inlet flap closes at 7%

7% of what? Make it `7% N ` or `N = 7%`. (I prefer the latter, because later on you use `N = 60%` in a different context)

> FAULT lt: [...]

Do we need to list every possible malfunction? 99% of our users won't understand it anyway.

**Overhead Fwd -> Auxiliary Power Unit-> START**

> ON: When N = 60%. The APU starter is de-energized. The ignition is turned off.

According to my docs it's 55%. 
At 55% the backup start contactor opens (from this moment there is no more power supply to the starter) and 5s later the start contactor opens (coincidence: this is at around 60% then).

**Overhead Fwd -> Cabin Pressurization-> MODE SEL**

> FAULT: Appears in amber and the ECAM caution light, when both automatic systems are faulty.

The part with the ECAM caution light sounds weird. 

**Overhead Fwd -> Calls Panel ->  Description**

> The flight interphone system is used for communication between the cockpit and the external service interphone panel, located at the nose gear.

I know what you mean, but the panel is not located at the nose gear. It's somewhat close to it, but it's in the fuselage. Airbus calls it the `External Power panel`. 

**Overhead Fwd -> Calls Panel ->  Usage -> MECH**

> The cockpit call light will illuminate on the **external service interphone panel**, and an external horn will sound. When the button is released, the horn is silenced. The cockpit call light will remain illuminated until the reset switch, located on the **external service interphone panel**, is pushed.

Same as above. The term "external service interphone" is especially problematic, because this jack is associated to the _flight interphone system_.

**Overhead Fwd -> Calls Panel ->  Usage -> FWD/AFT**

> A "CAPTAIN CALL" message will appear on the corresponding flight attendant indication panel.

Can you double-check your references for that? I'm pretty sure it says COCKPIT CALL (or CKPT CALL?), although I can't find any reference right now. If needed, I can check that out next time at work.
In general, I'm missing a note in this paragraph that explains that voice communication is established between the FAs station and the cockpit when the FA picks up the handset. But maybe it's not really needed...

**Overhead Fwd -> Cargo Smoke Panel ->  Usage -> SMOKE light**

> Both channels need to detect smoke, or one channel detects smoke and the SDCU finds that the other channel is faulty.

a) Reference to "both channels", without explanation what these channels are. An uninformed user could interpret this as "both the forward and aft cargo compartment need to sense smoke before the warning comes on". 
Question: Does the user really need to know what happens on such a detailed level? Isn't it enough to know "there is most probably smoke in the cargo"? If the answer is yes, then we should spend more words on explaining how the system works.
b) SDCUs don't exist in aircraft built after 2006. This function is now integrated in the CIDS, called CIDS-SDF (Smoke Detection Function).

**Overhead Fwd -> Cargo Smoke Panel ->  Usage -> DISCH light**

> Amber light comes on, indicating that the agent bottle has fully discharged.

Can we scratch "fully"? Because it comes on when the pressure drops below a certain threshold and it's rather far from "fully discharged".

**Overhead Fwd -> Electrical System Control Panel -> Usage -> AC ESS FEED**

Can we add a paragraph that in case of normal AC ESS Feed failure, the AC ESS Bus is automatically fed from AC BUS 2 after 5 seconds, regardless of the pushbutton position. This is correctly implemented in our aircraft by the way.

**Overhead Fwd -> Emergency Electric Power Panel -> Usage -> GEN 1 LINE**

> OFF: GEN 1 line contactor opens. The AC BUS 1 channel is supplied from GEN 2 through bus tie contactors. This is used for smoked drill.

I saw that you mostly copy&pasted this paragraph (including the typo ;) ) but I think we should point out the main function of this pushbutton a bit more. This is not incorrect, but pretty much fails to describe what makes this pushbutton so special. 
I can provide a more accurate description later and will open a separate issue for it, if that's ok for you.

**Overhead Fwd -> Fire Control Panel -> Usage -> APU FIRE**

> close low-pressure fuel valve and APU fuel pump.

[...] and turn off APU fuel pump 
(I know, but... you know... the fuel pump isn't "closed" ;) )

**Overhead Fwd -> Fire Control Panel -> Usage -> APU AGENT**

> Pushing it will **discharges** the respective fire bottle.

Discharge. Typo.

**Overhead Fwd -> Fire Control Panel -> Usage -> APU TEST**

> When **presses** there is a continuous repetitive chime sound

pressed. Typo.

**Overhead Fwd -> Fuel Control Panel -> Description**

> Each engine is fed by their corresponding **centre** and wing tanks

AE vs. BE. You use center everywhere else.

**Overhead Fwd -> Fuel Control Panel -> Usage -> CTR TK PUMP 1 + 2**

This is just a reminder for the future, not something that is actually wrong. And you probably know already. NEOs don't have center tank _pumps_ anymore. They have been replaced by _transfer valves_. Our current aircraft model has the wrong legends, which makes it kind of correct again.

**Overhead Fwd -> Fuel Control Panel -> Description**

> Only the last 30 minutes of recording is retained.

Aircraft built after 2003 have a 120 min recording time requirement. Airbus installs CVRs capable of 25h of recording since the end of 2020.

**Overhead Fwd -> Fuel Control Panel -> Usage -> CVR ERASE**

GND CTL must be on additionally.

**Comment by frankkopp** [comment]
Awesome - will look into it later today. 
Thanks so much!

**Comment by frankkopp** [comment]
APU Bleed:
![image](https://user-images.githubusercontent.com/16833201/133432359-ed780c0b-ebf2-4b8b-a69c-178d7a80dcf9.png)

Nothing more on fault causes

**Comment by frankkopp** [comment]
APU Bleed:
![image](https://user-images.githubusercontent.com/16833201/133432359-ed780c0b-ebf2-4b8b-a69c-178d7a80dcf9.png)

Nothing more on fault causes> To be precise, one fuel pump in the left wing tank is sufficient. The control depends on fuel pressure availability, not the status of the fuel pump. Could be renamed into "if at least one fuel pump in the left wing tank is in operation".

APU Fuel Pump:
![image](https://user-images.githubusercontent.com/16833201/133443616-9c4baa43-97be-400d-bb09-519ca2c875f1.png)

Also:

>> FAULT lt: [...]

> Do we need to list every possible malfunction? 99% of our users won't understand it anyway.

Probably not - I would be interested at least in the cases which could happen in the sim. I had cases with DC power lost (BAT OFF) in support a lot and maybe possible future failure scenarios (fire, etc.). Wdyt makes sense?

>>FAULT: Appears in amber and the ECAM caution light, when both automatic systems are faulty.

>The part with the ECAM caution light sounds weird.
![image](https://user-images.githubusercontent.com/16833201/133446502-07c739dd-dde6-4bda-9633-b2a8c1d742d6.png)

>> A "CAPTAIN CALL" message will appear on the corresponding flight attendant indication panel.

> Can you double-check your references for that? I'm pretty sure it says COCKPIT CALL (or CKPT CALL?), although I can't find any reference right now. If needed, I can check that out next time at work.
> In general, I'm missing a note in this paragraph that explains that voice communication is established between the FAs station and the cockpit when the FA picks up the handset. But maybe it's not really needed...

![image](https://user-images.githubusercontent.com/16833201/133447809-d562ea99-8353-4380-b073-bb08cd74bf90.png)

>> **Overhead Fwd -> Electrical System Control Panel -> Usage -> AC ESS FEED**

> Can we add a paragraph that in case of normal AC ESS Feed failure, the AC ESS Bus is automatically fed from AC BUS 2 after 5 seconds, regardless of the pushbutton position. This is correctly implemented in our aircraft by the way.

Could you double check on the corrected page that I got that right?

>> **Overhead Fwd -> Emergency Electric Power Panel -> Usage -> GEN 1 LINE**
>>  OFF: GEN 1 line contactor opens. The AC BUS 1 channel is supplied from GEN 2 through bus tie contactors. This is used for smoked drill.

> I saw that you mostly copy&pasted this paragraph (including the typo ;) ) but I think we should point out the main function of this pushbutton a bit more. This is not incorrect, but pretty much fails to describe what makes this pushbutton so special. 
I can provide a more accurate description later and will open a separate issue for it, if that's ok for you.

Please do but a DM on Discord is sufficient. (Cdr_Maverick#6475)

>> **Overhead Fwd -> Fuel Control Panel -> Usage -> CTR TK PUMP 1 + 2**

> This is just a reminder for the future, not something that is actually wrong. And you probably know already. NEOs don't have center tank _pumps_ anymore. They have been replaced by _transfer valves_. Our current aircraft model has the wrong legends, which makes it kind of correct again.

I made a note: The A320neo doesn't have center tank pumps anymore. These have been replaced by transfer valves. The current aircraft model used by the FlyByWire A32NX has incorrect labels.

See changes in the PR: https://github.com/flybywiresim/docs/pull/212
https://docs-git-fork-frankkopp-briefing-review-fixes-flybywire.vercel.app/pilots-corner/a32nx-briefing/flight-deck/

**Comment by komp1821** [comment]
Thanks! Good work as usual!

1) APU BLEED Fault light: I checked my docs and as far as I can tell I was wrong. At least I can't find any other condition for the light. So I guess it's correct as it is.

2) APU Fuel Pump: I have the same text in my "live" FCOM. This is one of the cases where the FCOM isn't totally wrong, but unprecise in my opinion. See Discord.

3) 
> Probably not - I would be interested at least in the cases which could happen in the sim. I had cases with DC power lost (BAT OFF) in support a lot and maybe possible future failure scenarios (fire, etc.). Wdyt makes sense?

I thought about it again and I think it should remain as it is. Yes, maybe some users won't understand all of it, but at least our documentation is complete. Otherwise we would have to hand pick the important things for every other indication, too.

4) CAPTAIN CALL: Good. Chances are that I'm wrong. Could also be an airline option. The CIDS is highly customizable. Let's leave it as it is.

5) 
> Could you double check on the corrected page that I got that right?

Perfect. Couldn't have worded it better!

---

I briefly looked over the rest of the changes. Most looked good. Is it possible that some of the changes haven't been pushed to the preview page yet? Example: https://docs-git-fork-frankkopp-briefing-mcdu-flybywire.vercel.app/pilots-corner/a32nx-briefing/flight-deck/ovhd/apu/ 
It still says starter cutout at 60% in the APU START pushbutton.

> Audio from the 3rd radio can be switched to either jump seat (NORM), CAPT or F/O.

Only thing to complain about: It should not be _radio_, it's the ACP (Audio Control Panel). It would also affect Flight and Cabin Interphone.

This might sound like nit-picking, but it is a difference :D

**Comment by frankkopp** [comment]
> I briefly looked over the rest of the changes. Most looked good. Is it possible that some of the changes haven't been pushed to the preview page yet? Example: https://docs-git-fork-frankkopp-briefing-mcdu-flybywire.vercel.app/pilots-corner/a32nx-briefing/flight-deck/ovhd/apu/
> It still says starter cutout at 60% in the APU START pushbutton.
> 
> Audio from the 3rd radio can be switched to either jump seat (NORM), CAPT or F/O.
> 
> Only thing to complain about: It should not be radio, it's the ACP (Audio Control Panel). It would also affect Flight and Cabin Interphone.
> 
> This might sound like nit-picking, but it is a difference :D

These should be fixed - at least I see it corrected:

![image](https://user-images.githubusercontent.com/16833201/133591050-f691b26d-ac87-42f0-be0b-6d86f7b4ee50.png)

![image](https://user-images.githubusercontent.com/16833201/133591001-c65aa911-e7d9-4646-b1a7-27c7ec710963.png)

Can you double check?

**Comment by komp1821** [comment]
Excellent! 

Nothing more to complain from my side!
