### ISSUE TITLE
Pilot Briefing: Glareshield & Instrument Panel - Accuracy Check

### ISSUE THREAD

**Issue by komp1821** [flybywiresim/docs#213]
### Summary

- [ ] **Glareshield -> EFIS Control Panel -> Description**
- [ ] **Glareshield -> Flight Control Unit -> Usage -> A/THR pushbutton**
- [ ] **Glareshield -> Warning Panel -> Usage -> 1. SIDE STICK PRIORITY**
- [ ] **Glareshield -> Warning Panel -> Usage -> 3. MASTER WARN**
- [ ] **Glareshield -> Warning Panel -> Usage -> 5. AUTOLAND WARNING LIGHT**
- [ ] **Instrument Panel-> Accumulator Pressure Indication -> Description**
- [ ] **Instrument Panel-> Accumulator Pressure Indication -> Description (2)**
- [ ] **Instrument Panel-> Autobrake and Gear Indications -> Usage -> L/G LEVER**
- [ ] **Instrument Panel-> Autobrake and Gear Indications -> Usage -> A/SKID & N/W STRG**
- [ ] **Instrument Panel-> Autobrake and Gear Indications -> Usage -> AUTO/BRK**
- [ ] **Instrument Panel-> Clock -> Description**

Hope this makes it easier for you to track the issues.

---

**Glareshield -> Flight Control Unit -> Usage -> A/THR pushbutton**

>The flight crew uses this button to arm, activate, or disconnect the autothrust (A/THR). Lights up in green if the A/THR is armed or active.

Same as above. Normal way to disconnect is by pushing the instinctive disconnect pushbutton on the thrust lever (or retarding the levers to idle). See `22_30-90 Autothrust -> A/THR Disconnection`

**Glareshield -> Warning Panel -> Usage -> 1. SIDE STICK PRIORITY**

> Green CAPT and F/O lights : Both lights **flash will flash** if the pilots are attempting to move both sidesticks at the same time and neither pilot takes priority.

a) Space between `lights` and `:` b) Typo/Careless mistake: `flash will flash` 

**Glareshield -> Warning Panel -> Usage -> 3. MASTER WARN**

>Provides an audible warning (repetitive **charms**, sounds, or a synthetic voice).

Chimes ;)

**Glareshield -> Warning Panel -> Usage -> 5. AUTOLAND WARNING LIGHT**

3x LDC. Should be LOC (as in localizer)

---

### Instrument Panel

**Instrument Panel-> Accumulator Pressure Indication -> Description**

> ACCU PRESS: Pressure in the yellow hydraulic system brake accumulators.

There's only one brake accumulator.

**Instrument Panel-> Accumulator Pressure Indication -> Description (2)**

> BRAKES: Yellow hydraulic system pressure delivered to the brakes. Measured upstream of the alternate servo valves.

Change to: Measured **down**stream of the **Direct Drive Valves**.

Another situation where the FCOM is to blame. The alternate brake system underwent a major overhaul in 2005-2006 and since then the "servo valves" in the alternate brake system are called Direct Drive Valves. The pressure transmitters are **down**stream of these valves. Everything else doesn't make sense because otherwise they would indicate brake pressure as soon as the NWS switch is selected to off, without the pedals being pushed. I cross checked this with the AMM.

**Instrument Panel-> Autobrake and Gear Indications -> Usage -> L/G LEVER**

> UP: The brake system brakes the wheels of the main gear and a brake band in the nose gear well brakes the nose gear wheels.

The brake band doesn't exist anymore in aircraft built since 2006. The NLG wheels just spin around until they stop eventually.
Even my latest NEO FCOM still has this paragraph, but it's just not true anymore.

**Instrument Panel-> Autobrake and Gear Indications -> Usage -> A/SKID & N/W STRG**

> ON: Lost green hydraulic pressure: Anti-skid remains available, while Nose wheel steering is lost.

Remove `while Nose wheel steering is lost`.
Nose wheel steering has been changed to the yellow hydraulic system in aircraft built since 2006, so you don't lose NWS with green hydraulic loss.

**Instrument Panel-> Autobrake and Gear Indications -> Usage -> AUTO/BRK**

> It has 4 settings: OFF, LO, MED and MAX.

Can we add a note that MAX can only be selected for takeoff and not when airborne? I get this question quite often (even from colleagues messing around with the flight sim "Hey komp, you know, the fbw Airbus you're working on... I found a bug: I can't select Auto Brake MAX for landing...")

I think we need to double check the parameters for auto braking. I remember there have been changes with the introduction of NEOs. I have these values in my FCOM (which includes both NEO and CEO). If the current values are the values we are using for our model, then everything is fine though.
![grafik](https://user-images.githubusercontent.com/71044068/133625538-4331783b-295d-4546-9d3a-975fa6eca4c8.png)

**Instrument Panel-> Clock -> Description**

> The A320neo has a build-in independent clock which sends time data to several systems. It has redundant electrical supply and is also directly connected to the aircraft's **battery hot bus**.

Hot Battery Bus, please :)

That's it again. Pedestal will follow in a separate issue.

**Comment by frankkopp** [comment]
> _If you disengage the AP with the buttons on the FCU, the cavalry charge will play continuously until the takeover pushbutton is pushed. If you press the takeover pushbutton, the cavalry charge plays 3 times and then turns off_

This is not implemented - IO made a note for this. 

> 3x LDC. Should be LOC (as in localizer)

That is actually an OCR and the copy&paste error :)

> I think we need to double check the parameters for auto braking. I remember there have been changes with the introduction of NEOs. I have these values in my FCOM (which includes both NEO and CEO). If the current values are the values we are using for our model, then everything is fine though.

Found this PR:
https://github.com/flybywiresim/a32nx/pull/4970
This confirms your values are implemented. I have changed the page accordingly. 

Changes pushed to https://docs-git-fork-frankkopp-briefing-review-fixes-flybywire.vercel.app/pilots-corner/a32nx-briefing/flight-deck/
