### ISSUE TITLE
Inaccuracies on Airliner Flying Guide-Approaches

### ISSUE THREAD

**Issue by kennedy4273** [flybywiresim/docs#227]
https://docs.flybywiresim.com/pilots-corner/airliner-flying-guide/approaches

The Airliner Guide on Approaches has some inaccuracies and omissions.

1. All references to CAT 1/2/3 should use Roman Numerals (CAT I/II/III) as that is the official classification.
2. The guide explains MDA and DH, but not DA. At least in the US, these are 3 distinct altitudes.
3. The links to example approach plates are broken, at least on PC on Chrome

Issue 2 means that several portions of the guide are inaccurate:

- The section explaining the different ILS categories refers to CAT I (and it's variants) using MDA, when they actually use a DA.
- The section explaining MDA and DH needs to include an explanation for DA. I propose the following addition, straight from the FAA Instrument Procedures Handbook  (FAA-H-8083-16B, Chapter 4):

> MDA—the lowest altitude, expressed in feet MSL, to which descent is authorized on final approach or during circle-to land maneuvering in execution of a standard instrument approach procedure (SIAP) where no electronic glideslope is provided.
> 
> DA—a specified altitude in the precision approach at which a missed approach must be initiated if the required visual reference to continue the approach has not been established.
> 
> DH—with respect to the operation of aircraft, means the height at which a decision must be made during an ILS, MLS, or PAR IAP to either continue the approach or to execute a missed approach. CAT II and III approach DHs are referenced to AGL and measured with a radio altimeter.

- The table in the MDA vs DH section should thus look something like this (also included references to Barometric and Radio):

Minimum Type | Defined As | Approaches Used in
---------------- | ------------- | --------------------
MDA (Minimum Descent Altitude) | Barometric Altitude Above Mean Sea Level | LOC, LDA, SDF, VOR, NDB, LNAV, ASR, Visual
DA (Decision Altitude) | Barometric Altitude Above Mean Sea Level | CAT I ILS, LNAV/VNAV, LPV, RNP, PAR, GLS
DH (Decision Height) | Radio Altitude Above Ground Level | CAT II/III ILS

**Comment by Valastiri** [comment]
The images included are being served from Wikipedia. While not the most ideal since they are being credited - slightly easier to just keep those offsite. Seemed to be a one-off unless you have specific instances you can drop here.
