### ISSUE TITLE
File missing to Thrustmaster TCA Quadrant Airbus Edition

### ISSUE THREAD

**Issue by volkerholloh** [flybywiresim/docs#262]
Hi there,

firstly I am BLOWN away what you people are doing @flybywiresim and I deeply appreciate your efforts and creativity.

On page [https://docs.flybywiresim.com/fbw-a32nx/a32nx-api/hardware/#thrustmaster-tca-quadrant-airbus-edition]("https://docs.flybywiresim.com/fbw-a32nx/a32nx-api/hardware/#thrustmaster-tca-quadrant-airbus-edition" ) there is a **duplicate** link to the quadrant add-on at both the quadrant and the quadrant add-on.

There is **no link** to the pdf of the **quadrant module itself**. I was searching for the file in this repo, but **could not find it**.

Kind regards,
Volker

**Comment by frankkopp** [comment]
> Hi there,
> 
> 
> 
> firstly I am BLOWN away what you people are doing @flybywiresim and I deeply appreciate your efforts and creativity.
> 
> 
> 
> On page [https://docs.flybywiresim.com/fbw-a32nx/a32nx-api/hardware/#thrustmaster-tca-quadrant-airbus-edition]("https://docs.flybywiresim.com/fbw-a32nx/a32nx-api/hardware/#thrustmaster-tca-quadrant-airbus-edition" ) there is a **duplicate** link to the quadrant add-on at both the quadrant and the quadrant add-on.
> 
> 
> 
> There is **no link** to the pdf of the **quadrant module itself**. I was searching for the file in this repo, but **could not find it**.
> 
> 
> 
> Kind regards,
> 
> Volker


Thanks for the report! Will look at in later today and fix it.

**Comment by frankkopp** [comment]
Checked it - as the PDF covers both I wanted to make sure each section has a link to the PDF. So this was intentional. 
Thanks for reporting though!
