### ISSUE TITLE
Throttle calibration guide possibly confusing with T.16000m, joystick only

### ISSUE THREAD

**Issue by nikidash** [flybywiresim/docs#308]
Hi, i just went through throttle calibration with a T.16000m. Joystick only, the more recent edition with the orange light.

I got stuck at step 5 of the section with the big red DO NOT SKIP warnings

> 5. Test
> Do not go on with the guide without successfully testing the following:
> 
>     The throttle in the cockpit should now move in the correct direction.
>     The throttle in the cockpit should move to TOGA when you set your controller to full thrust.
>     The throttle in the cockpit should move to IDLE when you set your controller to idle.
>     The throttle should move to full reverse if you activate reverse thrust on your controller. See Reverser Setup on how to engage reverser when you throttle does not have a reverser range.

Specifically the
>     The throttle in the cockpit should move to IDLE when you set your controller to idle.
part. At this point i had followed the guide step by step duplicating the default control profile to make a dedicated one for the Airbus, added a keybind to toggle reversers, and set all axes to fully linear as described in the guide. Despite this, when setting my physical throttle to idle, the aircraft throttle would go to full reverse, with the reverse toggle acting as a mere idle button like F1, it would just bring the throttle to idle with no changes to throttle behaviour.

Help from Discord made me find the issue, i had to continue to the EFB part of the setup to set the detents and deactivate the "reverser on axis" toggle. This is basically opposite to what the guide says, that you should repeat the DO NOT SKIP part if you do not meet the throttle behaviour "The throttle in the cockpit should move to IDLE when you set your controller to idle.". But to get that behaviour i needed to ignore that warning and continue to the EFB part of the guide.

**Comment by frankkopp** [comment]
Good point - need to describe it better for this specific case!

**Comment by frankkopp** [comment]
@nikidash would you mind reviewing the changes. Is it clearer now? 
Any other feedback will also be welcome!!
https://docs-git-fork-frankkopp-fix-throttle-calib-flybywire.vercel.app/fbw-a32nx/feature-guides/flyPad/throttle-calibration/

**Comment by frankkopp** [comment]
@nikidash will publish this change. If you still think it is unclear just open another issue.

**Comment by nikidash** [comment]
Sorry for the delay, only just got back to my pc. Seems ok now, the points that got me stuck are all addressed properly.
