### ISSUE TITLE
A new Standard Operating Procedures is in use and a new checklist!

### ISSUE THREAD

**Issue by Inaxair** [flybywiresim/docs#326]
Here is the link to the new SOP: 

[pdf/A32NX Documentation/FBW A32NX SOP.pdf](https://github.com/flybywiresim/manuals/blob/6dcb478cda6163d1e9c4979729bdf3cb9a23b6c8/pdf/A32NX%20Documentation/FBW%20A32NX%20SOP.pdf)

https://github.com/flybywiresim/manuals/blob/f13e14402bd029c960f712c8ac493a030a372a9b/pdf/A32NX%20Documentation/FBW%20A32NX%20Checklist.pdf

**Comment by Valastiri** [comment]
Using the `/manual` links to keep these updated. Just don't change the naming convention. Fixed in:
- #335
