### ISSUE TITLE
Taxi Guide: Add Tiller Link

### ISSUE THREAD

**Issue by MSVF** [flybywiresim/docs#377]
Hi,

little improvement idea: The [Taxi-Guide](https://docs.flybywiresim.com/pilots-corner/beginner-guide/engine-start-taxi/#during-taxi) mentions in the chapter "During Taxi", that the tiller is not implemented yet ("Use the tiller (currently not implemented) or rudder pedals to steer the aircraft)".
That changed recently (and btw. I love it), so you might want to [add the link to the new tiller function](https://docs.flybywiresim.com/fbw-a32nx/feature-guides/nw-tiller/?h=tiller) (+ the hint that is currently only available in the dev version).

Best

MSVF

**Comment by frankkopp** [comment]
Added - thanks!
