### ISSUE TITLE
Throttle calibration--a new way to mess up

### ISSUE THREAD

**Issue by OldAviator** [flybywiresim/docs#382]
Apparently it's possible to mess up the calibration of a one axis hardware throttle in such a way that the in-cockpit throttles operate independently of one another causing asymmetric thrust. I know, I did it. That's probably a UI problem that should be pointed out to the developers, but I thought it might be useful to include this possibility in the Troubleshooting section of the documentation. As far as I could figure out, the only way to address this is to delete the throttle config .ini file, which worked fine. Not a big deal, but it would save some people some time and frustration.

**Comment by frankkopp** [comment]
Thanks for the feedback.
This can easily solved by careful calibration of all detents - while calibrating the throttle in the cockpit does not matter until all detents are calibrated correctly and the values are applied. .

But we add a Reset to Default button soon: https://github.com/flybywiresim/a32nx/pull/6393
With this any misconfigurations can be reset as if the ini has been deleted. 

Will close this as the issues is addressed.
