### ISSUE TITLE
Flight Deck Guide: Summary of small hints

### ISSUE THREAD

**Issue by MSVF** [flybywiresim/docs#397]
Hi,

I had some time to read through the guides. I'm still learning so in terms of content I can not help so much, but at least I can provide some hints:

1. [FCU - APPR](https://docs.flybywiresim.com/pilots-corner/a32nx-briefing/flight-deck/glareshield/fcu/#appr): Typo: _Approach modes are activated **ot** deactivated_
2. [FCU - EXPED](https://docs.flybywiresim.com/pilots-corner/a32nx-briefing/flight-deck/glareshield/fcu/?h=exped#exped):  The EXP DES mode is well described here, but not part of the [PFD in-depth guide](https://docs.flybywiresim.com/pilots-corner/a32nx-briefing/pfd/second-column/)
3. [ECAM Control Panel](https://docs.flybywiresim.com/pilots-corner/a32nx-briefing/flight-deck/pedestal/ecam-control/#system-page-buttons): The info box mentions a future update in terms of detail description. But isn't that [this guide](https://docs.flybywiresim.com/pilots-corner/a32nx-briefing/ecam/sd/#ecam-system-display-pages) that you can link here?
4. [Flaps](https://docs.flybywiresim.com/pilots-corner/a32nx-briefing/flight-deck/pedestal/flaps/): Not sure who the target audience is, but if it's for dummies (me), the difference between CONF 1 and CONF 1 + F is not clear. For what does F stand for? I assume it stands for flaps. So CONF 1 gives slats 18 but flaps 0, while + F gives flaps 10
5. [MCDU](https://docs.flybywiresim.com/pilots-corner/a32nx-briefing/flight-deck/pedestal/mcdu/#description): The info box mentions a future update in terms of detailed guide. I think [this guide here](https://docs.flybywiresim.com/pilots-corner/beginner-guide/preparing-mcdu/) is already good enough to be linked here
6. [Radio - Transmission Keys #1](https://docs.flybywiresim.com/pilots-corner/a32nx-briefing/flight-deck/pedestal/rmp/#tansmission-keys): The box under the screenshot (_Currently only the VHF1-3 (...)_) feels misplaced, maybe it can be removed since it's covered in the the chapter "Reception Knobs"?
7. [Radio - Transmission Keys #2](https://docs.flybywiresim.com/pilots-corner/a32nx-briefing/flight-deck/pedestal/rmp/#tansmission-keys):"SELCAL" is mentioned in the chapter, while not explaining what it is. Sure I [googled](https://docs.flybywiresim.com/pilots-corner/a32nx-briefing/flight-deck/pedestal/rmp/#tansmission-keys) it, but would be handy to have it on one place. 
7. [Thrust Lever](https://docs.flybywiresim.com/pilots-corner/a32nx-briefing/flight-deck/pedestal/thrust-elev-trim/): In terms of THS and pitch trim, you might want to link to [this guide](https://docs.flybywiresim.com/pilots-corner/beginner-guide/preparing-mcdu/?h=ths#perf) to give more context

Other than that, keep up the good work and quality!!!

**Comment by frankkopp** [comment]
Thank you! for the feedback!

Fixes done. You can review if you like. 
https://github.com/flybywiresim/docs/pull/398

**Comment by MSVF** [comment]
I reviewed the changes based on your link, looks good to me. Thanks!
