### ISSUE TITLE
[BUG/ERROR] Old mod folder name in the "reported known issues page"

### ISSUE THREAD

**Issue by PierreLabs** [flybywiresim/docs#41]
## What is the bug/error?
On the ["reported known issues"](https://docs.flybywiresim.com/start/reported-issues/) page, the mod folder name still refers to the old naming convention (A32NX).

## Expected functionality
It should refer to the new folder name: "flybywire-aircraft-a320-neo".

## Steps to reproduce
---

## Additional information
![Capture d’écran 2021-04-04 201644](https://user-images.githubusercontent.com/4592920/113518283-9e107600-9585-11eb-8099-29b5f948d17f.png)

**Comment by Valastiri** [comment]
Re-opening as haven't merged it yet. I'll close it when ready just double-checking a few things to add in the same PR
