### ISSUE TITLE
MCDU Conf3 Approach page

### ISSUE THREAD

**Issue by AndreNL** [flybywiresim/docs#423]
When selecting Conf3 on the Approach page, this is not reflected in the LDG Checklist. Flaps Full is still required and Flaps 3 triggers EGPWS warnings on final.

**Comment by Valastiri** [comment]
If you are talking about the approach guide flaps 3 landing is not described (although we can add that in). It throws a EGPWS warning if you haven't selected `LDG FLAP 3` on the GPWS panel on the overhead found [here](https://docs.flybywiresim.com/pilots-corner/a32nx-briefing/flight-deck/ovhd/gpws/).

**Comment by AndreNL** [comment]
Yes sorry, just found out and also posted in the wrong section. Sorry, closing the issue.
