### ISSUE TITLE
FlyPadOS 3 Documentation

### ISSUE THREAD

**Issue by ErickSharp** [flybywiresim/docs#427]
- [ ] New structure
- [ ] New screenshots
- [ ] New content
- [ ] Update API for Checklist Item Completed LVAR
- [ ] Check other references/pages
	- [ ] Beginners Guide
	- [ ] /fbw-a32nx/feature-guides/web-mcdu/

**Comment by Valastiri** [comment]
Note: EFB content may be weaved within other documentation. Notable inclusions would be the beginner's guide. Will update this list with additional pages for tracking in case those images/instructions would need to be changed.

- *Pending List*
