### ISSUE TITLE
Some notes about the API docs

### ISSUE THREAD

**Issue by DarthJahus** [flybywiresim/docs#428]
1. In the docs, `BTN_LS_1_FILTER_ACTIVE` is said to not be working. However, another variable, `A320_NEO_PFD_BTN_LS_1`, that comes from the A320 Neo, works fine. Maybe that can help make the other one work?
1. On [this page](https://docs.flybywiresim.com/pilots-corner/a32nx-briefing/a32nx_api/#autobrake-gear-lever-and-gear-annunciation), the variable name for AUTO BRK LO/MED/MAX has a missing `s`.
> ![image](https://user-images.githubusercontent.com/7353366/153401236-1f3a00bd-407c-45d4-8e7e-9c891542ea5c.png)
1. In the APU panel section, for START function, the variables are presented as the same as for MASTER SW. However, the correct variables are `A32NX_OVHD_APU_START_SW_PB_IS_ON` and `A32NX_OVHD_APU_START_SW_PB_IS_AVAILABLE`.
> ![image](https://user-images.githubusercontent.com/7353366/153401197-aa5dfa8b-507e-4434-9b5c-30fabc577e94.png)

**Comment by DarthJahus** [comment]
The barometer knob in EFIS is not documented.

![image](https://user-images.githubusercontent.com/7353366/153609971-38b8875d-5f7d-4d51-a779-6849295a4d8f.png)

The variable for push/pull is `XMLVAR_Baro1_Mode`:
* Values: `0..2`
* Read/Write: `R/W`
* Type: `Custom LVAR`
* Remark: `0=QFE, 1=QNH, 2=STD`

Values `0` and `1` are cycled by pushing on the knob. Value `2` is achieved when you pull the knob.

Switching to `in Hg` and `hPa` is made by sending the events `XMLVAR_Baro_Selector_HPA_1_HPA` and `XMLVAR_Baro_Selector_HPA_1_IN` (not `_inHg`). The status is reflected in variable `XMLVAR_BARO_SELECTOR_HPA_1` (`0=inHg, 1=hPa`).

**Comment by frankkopp** [comment]
> 1. In the docs, `BTN_LS_1_FILTER_ACTIVE` is said to not be working. However, another variable, `A320_NEO_PFD_BTN_LS_1`, that comes from the A320 Neo, works fine. Maybe that can help make the other one work?

There is no such LVAR: A320_NEO_PFD_BTN_LS_1
![image](https://user-images.githubusercontent.com/16833201/153635158-6646787f-00aa-4136-8fc9-6b27dcf049da.png)

There are H:VARs but I have not documented these in general as they are very internal and harder to use. 
 
![image](https://user-images.githubusercontent.com/16833201/153639902-60f07e8c-a8e7-479b-b735-516df127e655.png)

> 2. On [this page](https://docs.flybywiresim.com/pilots-corner/a32nx-briefing/a32nx_api/#autobrake-gear-lever-and-gear-annunciation), the variable name for AUTO BRK LO/MED/MAX has a missing `s`.

fixed

> 1. In the APU panel section, for START function, the variables are presented as the same as for MASTER SW. However, the correct variables are `A32NX_OVHD_APU_START_SW_PB_IS_ON` and `A32NX_OVHD_APU_START_SW_PB_IS_AVAILABLE`.
> 
> > ![image](https://user-images.githubusercontent.com/7353366/153401197-aa5dfa8b-507e-4434-9b5c-30fabc577e94.png)

fixed

> Switching to `in Hg` and `hPa` is made by sending the events `XMLVAR_Baro_Selector_HPA_1_HPA` and `XMLVAR_Baro_Selector_HPA_1_IN` (not `_inHg`). The status is reflected in variable `XMLVAR_BARO_SELECTOR_HPA_1` (`0=inHg, 1=hPa`).

XMLVAR_Baro1_Mode added - was forgotten although I use it in my SPAD profile

Setting XMLVAR_BARO_SELECTOR_HPA_1 is documented correctly. 

This LVAR does not exist: XMLVAR_Baro_Selector_HPA_1_HPA or XMLVAR_Baro_Selector_HPA_1_IN
![image](https://user-images.githubusercontent.com/16833201/153638918-33b7038d-83dd-4f5e-84ff-b43522564777.png)

Fixes will be merged soon. 
Thanks for the report. 

https://github.com/flybywiresim/docs/pull/429

**Comment by DarthJahus** [comment]
Great!

About `XMLVAR_Baro_Selector_HPA_1_HPA` and `XMLVAR_Baro_Selector_HPA_1__IN`, they are events.

![image](https://user-images.githubusercontent.com/7353366/153647885-5d7ec958-3abb-469e-a09a-1f630b073313.png)

If I find anything else, I'll make sure to report it again. Feel free to close the issue.

**Comment by frankkopp** [comment]
> Great!
> 
> About `XMLVAR_Baro_Selector_HPA_1_HPA` and `XMLVAR_Baro_Selector_HPA_1__IN`, they are events.
> 
> If I find anything else, I'll make sure to report it again. Feel free to close the issue.

Don't think they are called LVAR Event...anyway where is this list from? Which tool?
 If you have a list maybe we can add it to the docs.

**Comment by DarthJahus** [comment]
In [External Lights panel documentation](https://docs.flybywiresim.com/pilots-corner/a32nx-briefing/a32nx_api/#external-lights-panel), there's a mistake in the WING section. `LIGHT WING` is written `LIGHT BEACON`.
![image](https://user-images.githubusercontent.com/7353366/155137575-faf114ae-d4cf-4ed0-b964-677c7284a098.png)

In the NOSE section, `NOSE T.O.` is written `NODE T.O.`
![image](https://user-images.githubusercontent.com/7353366/155137799-d04377a2-d619-497d-a4aa-ec0a54f48ef8.png)

In the STROBE section, `LIGHTING_STROBE_0` is shown to have values `0|1`, whilst it has `0..2` (as shown in remarks). It's shown to be `read only` whilst it's `R/W`. Tried it with SPAD.neXt and it can correctly change the values.
![image](https://user-images.githubusercontent.com/7353366/155138106-4188d331-5b27-4028-b3f0-694e9bcd6406.png)

About [ATC-TCAS panel](https://docs.flybywiresim.com/pilots-corner/a32nx-briefing/a32nx_api/#atc-tcas) and the `TRANSPONDER STATE:1` MSFS VAR, the remark says "probably more states". According to the description we can find in SPAD.neXt (not sure if it comes from MSFS or the software), the states are `1=STBY, 3=ON, 4=ALT`). This would need more investigation.
![image](https://user-images.githubusercontent.com/7353366/155138377-921a3755-4923-4af8-b198-45235c70aaf0.png)

Can't reopen the issue, but I think it's better for me to add these here instead of opening a new one. You tell me so I'll do what's better next time.
Thank you @frankkopp.

**Edit:**
As for the events `XMLVAR_Baro_Selector_HPA_1_HPA` and `XMLVAR_Baro_Selector_HPA_1_IN`, here they are. I don't know the correct word for these, but they are available in SPAD.neXt and work correctly with the A32NX.
![image](https://user-images.githubusercontent.com/7353366/155139888-84286e79-1cd4-4837-bde2-bcfa4f70c8fe.png)

**Comment by frankkopp** [comment]
@DarthJahus could you do a quick review? 
https://docs-git-fork-frankkopp-fix-api-flybywire.vercel.app/pilots-corner/a32nx-briefing/a32nx_api/
Thanks for pointing these out!

I also updated ATC/TCAS in general as these changed with merging TCAS.

**Comment by DarthJahus** [comment]
Everything seems good. Will apply the new TCAS changes. If I find anything else worth reporting, I'll do so.

Thank you!
