### ISSUE TITLE
Docs and Announcement for update of Simbrief API and W&B integration on A32NX

### ISSUE THREAD

**Issue by sidnov** [flybywiresim/docs#434]
https://github.com/flybywiresim/a32nx/pull/6701

From the PR,

`` Makes PAX_WEIGHT and BAG_WEIGHT dynamic to support the updated Simbrief API's <weights> section.
We are now able to pull separated weight values that can be customised on individual Simbrief airframes as per pilot/company requirements.
Default values are set to 84KGs (Pax weight+Cabin luggage) and 20KGs (check-in baggage per pax). Option to customize the default weight values without using Simbrief would be planned for the EFB load management interface. ``

In a nutshell, we now have the option to split pax and bag weights (made customisable, thanks to Simbrief).

What is required from the docs/media team:
The existing Simbrief airframe will be slightly modified and thus needs to be updated, we'll eventually need to send an announcement on social channels. Apart from this, I'll be glad to help add more details to our existing docs on how to customize the airframes to set your own custom weight configuration depending on the company/pilot.

![image](https://user-images.githubusercontent.com/29005005/153721064-2d1168fd-02df-4d2b-9f3c-540193865cb1.png)

**Comment by frankkopp** [comment]
@sidnov you have an ETA for your PR to be merged?

**Comment by sidnov** [comment]
> @sidnov you have an ETA for your PR to be merged?

pretty much ready on my side, unless any changes are requested. ETA of about 1 week, more or less
