### ISSUE TITLE
Where to enter Simbrief user?

### ISSUE THREAD

**Issue by paq99** [flybywiresim/docs#443]
I've been working through the beginner's guide and now want to import a Simbrief flightplan into the FMS/MCDU.  I've followed the steps in the guide under Simbrief integration but get an error at "INIT DATA REQ*" - "NO SIMBRIEF USER" shows at bottom of MCDU.  I assume this means I need to input my SIMBRIEF username somewhere, but the guide doesn't tell me where to do this (that I have seen) and I can't figure it out.  Any help with this would be appreciated.  Thanks

**Comment by Valastiri** [comment]
This is detailed on the [Preflight Page](https://docs.flybywiresim.com/pilots-corner/beginner-guide/preflight/) with links to the [Simbrief Integration Tutorial](https://docs.flybywiresim.com/fbw-a32nx/feature-guides/simbrief/). Please visit our Discord for extended support. Thanks!
