### ISSUE TITLE
Flybywire A320 StartUp

### ISSUE THREAD

**Issue by kalumantie** [flybywiresim/docs#474]
I am new to the A320, and I followed the beginner's guide from preflight to pushback from the gate and startup, but the engines would not start. I've watched several YouTube videos on startup, and I did what was recommended and still have the same issue. However, Strangely if I start the sim from a runway for taking off, the aircraft works fine.

**Comment by Valastiri** [comment]
@kalumantie Hey there this may seem like a #support issue for our Discord. I suggest you hop on in and ask our support team for troubleshooting and provide screenshots.

If you have followed the guide then everything should work as intended :).
