### ISSUE TITLE
Flopping throttles caused by conflicting profile

### ISSUE THREAD

**Issue by hiortintexas** [flybywiresim/docs#517]
I reported a problem with the flopping throttle levers on the Thrustmaster Airbus Throttle Quadrant - Came to find out that there was a conflicting profile active that also had the throttle mapped. Once that was fixed, no issue. (I use the new TurtleBeach Yoke and throttle quadrant, but even if the TB quadrant is disconnected, like in this case, the profile for it remains. So I had to put that profile to single engine as that does not have the throttle levers mapped).
I thought this could be helpful for some.

**Comment by Valastiri** [comment]
Additional feedback from user

> Right, the TurtleBeach yoke is two parts, the yoke and the throttle piece and in MSFS each have its own profile. So when I fly the A320, I disconnect the throttle and connect my Thrustmaster throttle instead.
However, the profile for the TB throttle is still active as I guess it is initiated by the yoke as the "main unit" so to speak. So care have to be given that that profile is not set to something that involves the throttles (or flaps or spoilers as I have the Thrustmaster extensions)

> For the TB quadrant you can have different profiles for e.g. a single engine, or a two engine jet etc. I ended up selecting the single engine as that only uses the push pull lever for throttle.
