### ISSUE TITLE
Triebwerke an

### ISSUE THREAD

**Issue by Marcel35HNT** [flybywiresim/docs#519]
Hallo, wenn ich den A320 FBW auf einer Startbahn starte also das Spiel, sind ja die Triebwerke bereits an, wenn das Spiel am Gate startet sind die Triebwerke usw. aus. gibt es eine Möglichkeit das dies beim Start auch bereits an ist ?

**Comment by Valastiri** [comment]
Hello! We typically take support questions on our social media or Discord :) as we use this repo for documentation issues. 

When starting at a gate the state of the aircraft is completely off imitating a cold and dark state. If you'd like to start with everything running starting on the runway is the choice.

Visit our Discord for extended support.
