### ISSUE TITLE
New gear system might need some additional info

### ISSUE THREAD

**Issue by crocket63** [flybywiresim/docs#537]
New gear system currently in review might need some explanations as there are new features coming with it:

Some new things/topics that might be good to mention (non exhaustive):
-Handle locked down mechanism
-Valve auto closed above 260kts
-Some failures added
-LGCIUs computers switch over when cycling gear lever
-Gravity extension available using dedicated ingame binding
-Door animations are NOT implemented yet due to model issues

**Comment by Valastiri** [comment]
Would have to find the best place to include this information! Thanks for the issue reminder :)

**Comment by crocket63** [comment]
Hope this will reach experimental soon, so maybe the first thing to mention is the binding for gravity extension.
"Keep pressing on GEAR_EMERGENCY_HANDLE_TOGGLE binding"

**Comment by Valastiri** [comment]
Issue taken care of with with PR:
- https://github.com/flybywiresim/docs/pull/557

Now available.
