### ISSUE TITLE
add wind requests feature 

### ISSUE THREAD

**Issue by Valastiri** [flybywiresim/docs#561]
Possibly to be included in the beginner guide rather than a separate feature.

Planning to be part of the MCDU section as it's related and good practice to have the wind requests in when configuring the aircraft.

Reference PR:
- https://github.com/flybywiresim/a32nx/pull/7158

**Comment by USA-RedDragon** [comment]
I'd be willing to write up some draft documentation to help this out if you want. I've got the Honeywell manual and did the implementation for wind requests, and KB-type articles are what I do often at work. 

It didn't even cross my mind, otherwise I'd have probably updated the docs with the PR
