### ISSUE TITLE
Rudder Pedals/Racing Pedals Compatibility

### ISSUE THREAD

**Issue by SteveCollins100** [flybywiresim/docs#568]
This might be useful for some people if your having problems using your racing pedals as rudders. After a recent update of the FBW A320 my rudders would not centre by themselves anymore using my racing pedals, I have found a workaround for this and thought I would share my findings so others can hopefully get theres working, so I mapped my Accelerator Pedal to Rudder Axis Right and my Clutch Pedal to Rudder Axis Left with both the reverse Axis boxes ticked. I then mapped the centre rudder to both pedals  and that has fixed my issue. Hope you dont mind me posting this here just thought it might help
![rudder](https://user-images.githubusercontent.com/105734830/168848748-fc93009b-4698-443b-8d54-8d50857560b7.png)
.

**Comment by Valastiri** [comment]
Thanks will get to this today :)
