### ISSUE TITLE
Simbrief 'Detailed Navlog' must be checked for correct flight plan import

### ISSUE THREAD

**Issue by Engin1980** [flybywiresim/docs#572]
Please note that 'Detailed Navlog' must be checked in the simbrief flight generating, otherwise the flight plan is not correctly imported (only departure and arrival icao are filled in the flightplan and 'AOC ACT F-PLN UPLINK' message never appears).

This information is important and is missing in the FBW documentation page.
Checked pages:
https://docs.flybywiresim.com/fbw-a32nx/feature-guides/simbrief/#request-data-from-simbrief
https://docs.flybywiresim.com/pilots-corner/beginner-guide/preparing-mcdu/

**Comment by Valastiri** [comment]
Hey there this was already handled :) in PR:
- https://github.com/flybywiresim/docs/pull/571

As for the beginner guide the page links to the simbrief dedicated page with the information now. The details are included here https://docs.flybywiresim.com/fbw-a32nx/feature-guides/simbrief/#importing-the-simbrief-ofp-to-the-flypad

If there was a place in beginner guide to include the warning let me know. I'll leave this open for a little bit while waiting for a response.
