### ISSUE TITLE
RNP Issue in Sydney 

### ISSUE THREAD

**Issue by Diogenes84** [flybywiresim/docs#585]
On the RNP approach to YSSY on 34L, I had a kink to the left directly in the glidepath between 1900ft and Rwy. I use Sydney Airport from Fly Tampa. No Problems with the Fenix.

**Comment by frankkopp** [comment]
This is the flybywire docs repo. Reports for the ircraft do not belong here. 

Also this is a really bad report with nearly no information to work with. If you think you need to report something please use the template in the a32nx repo and describe the issue in a way it can be reproduced. 

You can skip any comparison to other aircarft as these have no relevance. 

(Also RNP/RNAV is not yet implemented)
