### ISSUE TITLE
docs and bot prep needed for gross weight PR changes

### ISSUE THREAD

**Issue by sidnov** [flybywiresim/docs#589]
For PR https://github.com/flybywiresim/a32nx/pull/7291/

GW value on the ECAM now appears more accurately- only when certain conditions are satisfied

MCDU INIT B should have ZFW/ZFWCG input.
MCDU FUEL PRED should have ZFW/ZFWCG input.
and
one of the engines are start up

GW is calculated as fuel quantity (using fuel flow on engine start) + ZFW input in the MCDU.

When there is a GW mismatch of more than 7 tons between the values calculated aerodynamically and the value calculated using the input ZFW and fuel flow, "CHECK WEIGHT" shows up on the MCDU Scratchpad.

When any one engine is startup with the INIT B ZFW/ZFWCG left unfilled, "INITIALIZE WEIGHT/CG" appears on the scratchpad.

![image](https://user-images.githubusercontent.com/29005005/177036297-6b1653ba-82ed-4006-8b66-5a7a63280d82.png)

Common issues that will be encountered in support:
Pilots not initializing values in INIT B before engine start. Expected message- "INITIALIZE WEIGHT/CG"
Pilots unaware of loading/fueling, carrying the wrong weights while using the correct ZFW values from Simbrief. Expected message- "CHECK WEIGHT". This will most likely appear a few seconds post takeoff/wheels up.

**Comment by Valastiri** [comment]
Pages to update:

- Add a note to beginner guide
- W/B
