### ISSUE TITLE
API ENG panel

### ISSUE THREAD

**Issue by schroewo** [flybywiresim/docs#616]
The documentation of the ENG Panel https://docs.flybywiresim.com/pilots-corner/a32nx-briefing/a32nx_api/#eng-panel seems to be not correct.
The TURB ENG IGNITION SWITCH EX1 can only be read and needs an index of 1(or 2, why?) to get the correct position of the mode switch.
When I tried to read the TURB ENG IGNITION SWITCH EX2, I get an error ‘Could not resolve Variable ID….’.

**Comment by frankkopp** [comment]
It is writable but indeed naming was wrong - needs to be
TURB ENG IGNITION SWITCH EX1:1
TURB ENG IGNITION SWITCH EX1:2
Fixed

Thanks for the report.
