### ISSUE TITLE
Update flyPad 2 screenshots on calibration guide

### ISSUE THREAD

**Issue by Oyu07** [flybywiresim/docs#729]
Throttle calibration page still has flyPad 2 screenshots
<https://docs.flybywiresim.com/fbw-a32nx/feature-guides/flypados3/throttle-calibration/#thrustmaster-tca-throttle>
![image](https://user-images.githubusercontent.com/66401072/216618461-3d1b4568-5cd4-4eec-b664-b9dcde95f035.png)

**Comment by Valastiri** [comment]
Thanks we'll probably update this with some free time set aside as noted on Discord.
