### ISSUE TITLE
Adjust hold standards speed table

### ISSUE THREAD

**Issue by a-bern** [flybywiresim/docs#751]
The icao speed limits table at https://docs.flybywiresim.com/pilots-corner/advanced-guides/flight-planning/holds/#hold-standards should be slightly modified:

```
Altitude (ft MSL)	Airspeed (KIAS)
<= 14000	230
14001 - 20000	240
20001 - 34000	265
> 34000	.83 Mach
```

Reference: https://skybrary.aero/articles/holding-pattern

**Comment by Valastiri** [comment]
Thanks! Took me a minute to see where the changes were. I think instead of using `14001` we might instead use the terminology `Above 14000 up to 20000` to increase clarity.

Will create a PR for this unless you open one ahead of time :). Cheers!

**Comment by tracernz** [comment]
The current table is consistent with the Honeywell A320 FMS documentation so I suggest we retain it.

**Comment by Valastiri** [comment]
Review provided: https://github.com/flybywiresim/docs/pull/753#pullrequestreview-1323091994

Thanks for looking into the speeds but since they are correct will be closing this issue.

**Comment by a-bern** [comment]
> The current table is consistent with the Honeywell A320 FMS documentation so I suggest we retain it.

I dont get your point. With the current documentation its not clear whether you have to fly at a max speed of 265 or 240 at an altitude of 20000 ft. The table in this documentation talks about „icao speed limits“. And the icao speed limits are very clear on this topic.

Its rather cosmetic/clarification change. Either remove the table and link to the official icao speed table or adjust the fbw documentation.

**Comment by tracernz** [comment]
> 

We work from the Honeywell A320 FMS documentation which has a slightly different table to Skybrary (perhaps a slightly different interpretation of the ICAO source document). Since this is the FMS we are modelling that is our source of truth, and what the FMS implementation is based off. I do agree that the 20000 is ambiguous, but that is how it exists in their table.. :/
