### ISSUE TITLE
deboarding on payload page

### ISSUE THREAD

**Issue by Sleinmaster** [flybywiresim/docs#755]
https://docs.flybywiresim.com/fbw-a32nx/feature-guides/flypados3/ground/?h=payload#payload-page
https://docs.flybywiresim.com/fbw-a32nx/feature-guides/loading-fuel-weight/#development-version

These two pages should be updated with the "new" boarding/deboarding buttons implemented in https://github.com/flybywiresim/a32nx/pull/7604

**Comment by Luz5020** [comment]
https://docs.flybywiresim.com/fbw-a32nx/feature-guides/loading-fuel-weight/#development-version
That page contains many images for the Weight managment Tutorial, should all Images containing the payload page be changed? Or only the ones where the button is explicitly mentioned?

**Comment by Sleinmaster** [comment]
I would update all of them, but maybe you can ask in discord first what Val and Mav think.

**Comment by Luz5020** [comment]
Mav already said he'd like to check the screenshots again when they're done so i'll just retake every image where the boarding page is visible
