### ISSUE TITLE
Change admonition for CG sclae in cockpit

### ISSUE THREAD

**Issue by frankkopp** [flybywiresim/docs#780]
See https://github.com/flybywiresim/a32nx/pull/7931

**Comment by frankkopp** [comment]
@Luz5020 - you want to tackle this?
https://docs.flybywiresim.com/pilots-corner/beginner-guide/engine-start-taxi/#after-engine-start

Could also use a new screenshot of the scale now.

![image](https://user-images.githubusercontent.com/16833201/229482842-2318885f-b93d-47b9-a343-e67b64db74d6.png)

**Comment by Luz5020** [comment]
Sure, I can update the Screenshot

**Comment by frankkopp** [comment]
> 
Thanks!
The admonition text should also change to reflect that only Stable has the wrong CG scale

**Comment by Luz5020** [comment]
I‘ll get on that, Screenshot may take a few days, when I‘m back at my Sim

**Comment by Luz5020** [comment]
> > 
> 
> Thanks! The admonition text should also change to reflect that only Stable has the wrong CG scale

Wondering if we need the admonition? [Here](https://github.com/flybywiresim/docs/pull/775#issuecomment-1489782828) it was mentioned it could be completely removed if the change comes to Dev

**Comment by frankkopp** [comment]
> > > 
> > 
> > 
> > Thanks! The admonition text should also change to reflect that only Stable has the wrong CG scale
> 
> Wondering if we need the admonition? [Here](https://github.com/flybywiresim/docs/pull/775#issuecomment-1489782828) it was mentioned it could be completely removed if the change comes to Dev

We still need it as the change does not go to Stable directly. Just to Dev.
Once we have a new Stable version that admin can be removed

**Comment by Luz5020** [comment]
I was just wondering, since in the PR I mentioned I was instructed to take it out completely, even though it was still relevant for Stable
