### ISSUE TITLE
Change of fuel system missing in the flight deck API page

### ISSUE THREAD

**Issue by Sleinmaster** [flybywiresim/docs#792]
https://docs.flybywiresim.com/fbw-a32nx/a32nx-api/a32nx-flightdeck-api/#fuel-panel

FUELSYSTEM_PUMP_TOGGLE 1 and 4 for the center tank pump switches don't work anymore because there are no pumps in the neo, which got corrected in a recent update.
The new vars or events for these buttons are FUELSYSTEM_VALVE_TOGGLE 9 and 10.

See conversation in the following message.

https://discord.com/channels/738864299392630914/785976111875751956/1096138962898276383

Pr for the change was https://github.com/flybywiresim/a32nx/commit/f7e6b5014b9b613d9f0662921333346e86494393

**Comment by Valastiri** [comment]
I can have a look at this tonight.
