### ISSUE TITLE
A32NX does now autotune navaids

### ISSUE THREAD

**Issue by BlueberryKing** [flybywiresim/docs#801]
Apologies if this has been reported already, but we should remove this part or add an admonition for Stable here, as the A32NX does now autotune navaids.
https://docs.flybywiresim.com/pilots-corner/beginner-guide/descent/#at-10000ft-procedure

Also, "NAVA/OS" should probably be "navaids".

![image](https://user-images.githubusercontent.com/22713769/232493327-27ebd5bc-fbb7-43f5-be09-6e638a021efc.png)

**Comment by Valastiri** [comment]
Thanks just something we haven't gotten round to yet -- I'll take a look at it tonight time permitting.
