### ISSUE TITLE
Remove Mention of Stable In WX Radar Panel Page

### ISSUE THREAD

**Issue by JasonO99** [flybywiresim/docs#809]
https://docs.flybywiresim.com/pilots-corner/a32nx-briefing/flight-deck/pedestal/radar/#mode-display-mode-selector

![image](https://user-images.githubusercontent.com/2074263/233834279-26772fa0-9289-4d33-94de-28f8ec50146b.png)

Underneath the **MODE - Display mode selector** heading it makes mention of the different WX panel controls, to adjust the WX radar display. The box below it states it is not available in 'Stable'; when actually it is not available in any version at this moment in time.

Suggested alternative (based on the wording of other sections about missing features on the FBW aircraft);
_Weather is currently not available or INOP in the FBW A32NX. We are awaiting Asobo API implementation. See [Custom FMS Special Notes](https://docs.flybywiresim.com/fbw-a32nx/feature-guides/cFMS/#special-notes)_

**Comment by Valastiri** [comment]
Opened a pull request if you'd like to take a look.
