### ISSUE TITLE
50% N1 not 50% thrust for initial takeoff power set

### ISSUE THREAD

**Issue by donstim** [flybywiresim/docs#821]
The technique for setting takeoff thrust in the beginner's guide says to first set 50% thrust (see screenshot). This should say to set 50% N1. 50% thrust and 50% N1 are not the same thing.

![Screenshot (2713)](https://user-images.githubusercontent.com/70166617/236576821-14049610-451b-4910-9340-26041a894240.jpg)

**Comment by Luz5020** [comment]
so the docs should say something along the lines of: "increase thrust so N1 rises to approx 50%" ?

**Comment by donstim** [comment]
Sure. Or just replace "50% thrust" with "50%N1."
