### ISSUE TITLE
HOT AIR on flight deck API documentation

### ISSUE THREAD

**Issue by BlueberryKing** [flybywiresim/docs#831]
Hi, small issue on the flightdeck API noticed on Discord. This is due to a recent change.

On https://docs.flybywiresim.com/fbw-a32nx/a32nx-api/a32nx-flightdeck-api/#air-condition-panel, the HOT AIR toggle is controlled by `A32NX_OVHD_COND_HOT_AIR_PB_IS_ON` and the fault light is represented in `A32NX_OVHD_COND_HOT_AIR_PB_HAS_FAULT`.

Thank you for having a look at this. 😄

**Comment by JasonO99** [comment]
Page updated to reflect changes on the above PR, which has been merged.

**Comment by Valastiri** [comment]
Closing as resolved.
