### ISSUE TITLE
Wrong discord usernames 

### ISSUE THREAD

**Issue by Lauvaan** [flybywiresim/docs#841]
After the new username update, at least straks', oim's and benw's usernames need changing in [https://docs.flybywiresim.com/dev-corner/development-projects/discord-bot/](https://docs.flybywiresim.com/dev-corner/development-projects/discord-bot/), some other usernames might need changing in other places as well, not sure.

**Comment by Valastiri** [comment]
I found it hilarious that the link in your issue links to this actual issue instead of the page. Do you mean it needs updating to the new Discord usernames? 

Edit: Linked a PR -- let me know if that's good in here or the PR itself.

**Comment by Lauvaan** [comment]
> I found it hilarious that the link in your issue links to this actual issue instead of the page. Do you mean it needs updating to the new Discord usernames? 
> 
> Edit: Linked a PR -- let me know if that's good in here or the PR itself.

Yep, looks good. Also, the link didn't link anywhere 🤦
