### ISSUE TITLE
correct format of g load

### ISSUE THREAD

**Issue by Sleinmaster** [flybywiresim/docs#843]
The g for g load should be formatted in italic and without space after the number.

`grams: 1 g`
`g load: 1*g*`

should be corrected on these pages:
docs/pilots-corner/a32nx-briefing/ecam/sd/index.md
docs/pilots-corner/advanced-guides/protections/overview.md
docs/pilots-corner/advanced-guides/protections/abnormallaw.md
docs/fbw-a32nx/feature-guides/custom-hydraulics.md
docs/pilots-corner/a32nx-briefing/limitations.md

**Comment by Valastiri** [comment]
I can look at this tomorrow if you don't get to it before me.
