### ISSUE TITLE
Info on MAX Manual breaking

### ISSUE THREAD

**Issue by Valastiri** [flybywiresim/docs#865]
Add some information on max manual breaking procedure for A32NX.

@tshomas can provide some insight as per discussions on discord

**Comment by tshomas** [comment]
Righto got the proper lowdown and accurate statements:

If MAX manual braking is to be used:
Auto brake medium must be selected.
Reverser MAX must be selected at touchdown.
Pilot flying will override the autobrake on nosewheel touchdown and apply maximum braking pedal deflection.

That should be good!
