### ISSUE TITLE
Document ground air start feature 

### ISSUE THREAD

**Issue by Valastiri** [flybywiresim/docs#900]
Documenting the following feature from A32NX:

- https://github.com/flybywiresim/aircraft/pull/8240

**Comment by Maximilian-Reuter** [comment]
Ha I was just about to ask about documentation regarding this

**Comment by Valastiri** [comment]
@Maximilian-Reuter just keeping myself posted -- let me know when things are ready -- most I'd ask for help with is just a screenshot of the EFB with the Air Start and any other changed page // similar to what we have already cuz that will 100% need updating aside from any text

**Comment by Maximilian-Reuter** [comment]
I have added a screenshot to the PR which should be usable for the documentation. 
Someone would probably also need to handle the added localization string

**Comment by Maximilian-Reuter** [comment]
PR is pretty much ready for release
I would suggest a ground air start procedure entry like for crossbleed starts already exists
Speaking of, this page would also need updates: https://docs.flybywiresim.com/pilots-corner/advanced-guides/engines/crossbleed-start/

**Comment by Maximilian-Reuter** [comment]
I also updated the EFB image in my PR since I changed the Icon

**Comment by Valastiri** [comment]
Sorry been incredibly busy I see the Discord post as well will look into it

**Comment by Maximilian-Reuter** [comment]
hahaha, no worries, shomas said he would write up some procedure for the ground start
