### ISSUE TITLE
Typo in "A32NX Flight Deck API" - "EFIS Control Panel"

### ISSUE THREAD

**Issue by HansBilliet** [flybywiresim/docs#924]
Just found a typo in one of your commands. The 'Baro knob SIMCONNECT EVENT' should be:

- KOHL**S**MAN_INC
- KOLH**S**MAN_DEC

This seems wrong in the doc:

![image](https://github.com/flybywiresim/docs/assets/5977382/b987cdb8-b413-4cf1-abe5-e24cac3a99b8)

**Comment by Valastiri** [comment]
@frankkopp Would you mind verifying since you usually handle this page for us :) thanks in advance.

**Comment by HansBilliet** [comment]
And while you're dealing with this one, there seem a few more issues.

'**LIGHT POTENTIOMETER:NN**' are MSFS VAR that are NON editable. In your documentation it says:
![image](https://github.com/flybywiresim/docs/assets/5977382/feb80759-a06a-4d7c-b249-121363ae51d1)

But the SDK Documentation shows:
![image](https://github.com/flybywiresim/docs/assets/5977382/c8ed8bdb-8888-4ff7-b133-9bd091125d83)

If you want to set the value of a LIGHT_POTENTIOMETER, you need to use an SimConnect Event with 2 parameters.
![image](https://github.com/flybywiresim/docs/assets/5977382/5f2952cb-1d4f-4c08-84d1-38b7810416e4)

This means that you have to use the '**SimConnect_TransmitClientEvent_EX1**' in which dwData0 is the index and dwData1 is the value.

I tested the above, and it works perfectly for A32NX.

**Comment by frankkopp** [comment]
> I tested the above, and it works perfectly for A32NX.

We know this works perfectly as we use it in several places - this is merely a documentation issue,.
