### ISSUE TITLE
Update beginner guide Setup MCDU route

### ISSUE THREAD

**Issue by frankkopp** [flybywiresim/docs#938]
https://docs.flybywiresim.com/pilots-corner/beginner-guide/preparing-mcdu/#flight-plan

![image](https://github.com/flybywiresim/docs/assets/16833201/2ad1cc8d-ee02-4341-87db-7c123765cadf)

Example:
![image](https://github.com/flybywiresim/docs/assets/16833201/52a47e03-8031-4d9c-9bec-00a67bc8aa7c)

**Comment by Valastiri** [comment]
Oh my this will require a bunch of updates to the page in general
